config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'

  resources :boards do
    resources :posts
  end

  resources :invitations, only: [:create, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  has_and_belongs_to_many :users

  has_many :posts, dependent: :destroy

  validates :title, presence: true
  validates :slug, presence: true, uniqueness: true
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  has_secure_token

  belongs_to :board
  belongs_to :inviter, class_name: :User, foreign_key: 'inviter_id'
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :board
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_and_belongs_to_many :boards

  has_many :invitations, foreign_key: 'inviter_id'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_board, only: [:show]

  def new
    @board = Board.new
  end

  def create
    board = Board.new(create_params)
    board.users<< current_user
    if board.valid?
      board.save
      redirect_to action: 'index'
    else
      @board = board
      render template: 'boards/new'
    end
  end

  def index
    @boards = current_user.boards
  end

  # GET /boards/1
  # GET /boards/1.json
  def show
  end

  private

  def create_params
    params.require(:board).permit(:title, :slug)
  end

  def set_board
    @board = Board.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @user = current_user
  end
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  before_action :authenticate_user!

  def create
    puts 'creating invite'
    @invite = Invitation.create!(board_id: params[:board_id], inviter: current_user, expires: 7.days.from_now)
    puts "created #{@invite}"
    redirect_to action: 'index'
  end

  def index
    @invitations = current_user.invitations
  end

  private

  def create_params
    params.require(:board)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
    @post.board = Board.find(params[:board_id])
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to board_post_path(@post.board, @post), notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to board_post_path(@post.board, @post), notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to board_posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :url, :board_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/boards/_list.html.erb
<div>
<% boards.each do |b| %>
  <p><%= b.id %>: <%= link_to b.title, b %></p>
<% end %>
</div>

app/views/boards/index.html.erb
<h1>Boards</h1>
<%= link_to 'Create Board', controller: 'boards', action: 'new' %>
<%= render 'list', boards: @boards %>

app/views/boards/new.html.erb
<h1>Create Board</h1>

<% if @board.errors.any? %>
  <div id="error_explanation">
    <ul>
    <% @board.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @board, url: { action: 'create' }  do |f| %>
  <p>Title: <%= f.text_field :title %></p>
  <p>Slug: <%= f.text_field :slug %></p>
  <p><%= f.submit %></p>
<% end %>

app/views/boards/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @board.title %>
</p>

<p><%= link_to 'Invite someone', {controller: 'invitations', action: :create, board_id: @board}, method: :post %></p>

<p>
  <strong>Posts:</strong>
  <%= link_to 'New Post', new_board_post_path(board_id: @board) %>
  <div>
  <% @board.posts.each do |p| %>
    <p><%= p.id %>: <%= link_to p.title, p.url %></p>
  <% end %>
  </div>
</p>

<%= link_to 'Back', boards_path %>

app/views/home/index.html.erb
<h1>Hello, world!</h1>
<% if @user == nil %>
  <p><a href="/users/sign_up">Sign Up</a></p>
  <p>Have an account? <a href="/users/sign_in">Sign In</a></p>
<% else %>
  <p><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></p>
  <%= render 'boards/list', boards: @user.boards %>
<% end %>

app/views/invitations/index.html.erb
<p>Current invitations:</p>
<div>
  <ul>
    <% @invitations.each do |invite| %>
      <li><%= invite.token %>, Expires: <%= invite.expires %></li>
    <% end %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Miranda</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: [board, post], local: true) do |form| %>
  <%= form.hidden_field :board_id %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', board: @post.board, post: @post %>

<%= link_to 'Show', board_post_path(@post.board, @post) %> |
<%= link_to 'Back', board_posts_path %>

app/views/posts/index.html.erb
<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Url</th>
      <th>Board</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.url %></td>
        <td><%= post.board %></td>
        <td><%= link_to 'Show', board_post_path(post.board, post) %></td>
        <td><%= link_to 'Edit', edit_board_post_path(post.board, post) %></td>
        <td><%= link_to 'Destroy', board_post_path(post.board, post), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_board_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post, board: @post.board %>

<%= link_to 'Back', board_posts_path %>

app/views/posts/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Url:</strong>
  <%= @post.url %>
</p>

<p>
  <strong>Board:</strong>
  <%= link_to @post.board.title, @post.board %>
</p>

<%= link_to 'Edit', edit_board_post_path(@post) %> |
<%= link_to 'Back', board_posts_path %>